/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(_DWORD); weak
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD); weak
// void *malloc(size_t size);
// void *memset(void *s, int c, size_t n);
// void free(void *ptr);
// int strcmp(const char *s1, const char *s2);
// void *dlopen(const char *file, int mode);
// void *dlsym(void *handle, const char *name);
// int dlclose(void *handle);
// int __fastcall _stack_chk_fail(_DWORD); weak
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// int __fastcall _aeabi_memcpy(_DWORD); weak
// int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD); weak
// int dladdr(void); weak
// int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_8C8();
int (*__fastcall sub_8E8(int (*result)(void)))(void);
signed int OMX_Init();
int OMX_Deinit();
signed int __fastcall sub_C0C(char *a1);
signed int __fastcall sub_C84(int a1);
signed int __fastcall OMX_GetHandle(_DWORD *a1, char *a2, int a3, int a4);
signed int __fastcall sub_1110(int a1, _DWORD *a2, signed int *a3);
signed int __fastcall sub_11C4(int a1);
signed int __fastcall OMX_FreeHandle(int a1);
signed int __fastcall sub_13C4(int a1, int a2, unsigned int a3, unsigned int a4);
signed int __fastcall sub_1704(int a1, int a2, unsigned int a3, int a4, int *a5);
signed int __fastcall sub_17A8(int a1, int a2, unsigned int a3, int a4);
signed int __fastcall sub_18D0(int a1, int a2, int a3);
void sub_1924();
void sub_192C();
signed int __fastcall sub_19C8(int a1, int a2, char a3);
void __fastcall sub_1AE4(int a1, int a2, int a3);
int __fastcall sub_1B68(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_1B80(int _R0);
int __fastcall sub_1B88(int _R0);
int __fastcall sub_1B90(int _R0);
void sub_1B98();
void sub_1BDC();
int __fastcall sub_1BF0(int a1);
signed int __fastcall sub_1C40(int a1, int a2, _DWORD *a3);
signed int __fastcall sub_1C70(int a1, int a2, int a3);
signed int __fastcall sub_1CB4(int a1, int a2, _QWORD *a3);
signed int __fastcall sub_1CE4(int a1, int a2, int a3, int a4);
int __fastcall sub_1D1C(int a1);
signed int __fastcall sub_1D24(int a1, int a2);
signed int __fastcall sub_1D44(int a1);
int __fastcall sub_1D5C(int a1);
int __fastcall sub_1D6C(int a1, int a2);
int __fastcall sub_1D8C(int a1, signed int a2);
int __fastcall sub_1E28(int result, signed int a2, int a3);
int __fastcall sub_1EC0(int a1, int a2);
__int64 __fastcall sub_1EE0(int a1, int a2);
int __fastcall sub_1F90(int a1, int a2, int a3, int a4);
signed int __fastcall sub_2064(int a1);
int __fastcall sub_20B0(int a1, int a2);
void __fastcall sub_20E8(int a1);
int __fastcall sub_2100(int a1);
signed int __fastcall sub_2108(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_2164(int a1, int a2);
const char *__fastcall sub_21B4(int a1, signed int a2);
int __fastcall sub_21BC(int result);
void __fastcall sub_21C4(int a1, int a2, int a3, int a4);
int __fastcall sub_21F8(int a1);
int sub_224C(); // weak
int __fastcall sub_23D4(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int sub_2AA8(); // weak
int __fastcall sub_2ABC(int _R0);
int __fastcall sub_2AC4(int _R0);
int __fastcall sub_2ACC(int _R0);
int __fastcall sub_2AD4(_DWORD *a1);
int __fastcall sub_2B18(_DWORD *a1);
void sub_2B2C();
void sub_2B30();
int __fastcall sub_2B3C(_DWORD *a1);
int __fastcall sub_2B40(_DWORD *a1);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_18D8; // weak
char *off_4E20[4] =
{
  "OMX.qcom.image.jpeg.encoder",
  "libqomx_jpegenc.so",
  "OMX.qcom.image.jpeg.decoder",
  "libqomx_jpegdec.so"
}; // weak
void *off_4E38 = (void *)0x1D65; // weak
int GLOBAL_OFFSET_TABLE_ = 0; // weak
void *off_5000 = &off_5000; // weak
int dword_5004; // weak
_UNKNOWN unk_5008; // weak
int dword_500C; // weak
_UNKNOWN unk_5010; // weak
// extern _UNKNOWN _stack_chk_guard; weak
// extern struct _IO_FILE *stderr;


//----- (000008C8) --------------------------------------------------------
int sub_8C8()
{
  return _cxa_finalize(&off_5000);
}
// 7CC: using guessed type int __fastcall _cxa_finalize(_DWORD);
// 5000: using guessed type void *off_5000;

//----- (000008E8) --------------------------------------------------------
int (*__fastcall sub_8E8(int (*result)(void)))(void)
{
  if ( result )
    result = (int (*)(void))result();
  return result;
}

//----- (000009A8) --------------------------------------------------------
signed int OMX_Init()
{
  signed int v0; // r3@2
  signed int v2; // [sp+Ch] [bp-14h]@1
  signed int i; // [sp+10h] [bp-10h]@6

  v2 = 0;
  pthread_mutex_lock((pthread_mutex_t *)&unk_5008);
  if ( dword_5004 )
  {
    ++dword_500C;
    pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
    v0 = 0;
  }
  else
  {
    dword_5004 = (int)malloc(0x8Cu);
    if ( dword_5004 )
    {
      memset((void *)dword_5004, 0, 0x8Cu);
      for ( i = 0; i < 2; ++i )
      {
        *(_DWORD *)(44 * i + dword_5004 + 36) = off_4E20[2 * i];
        *(_DWORD *)(44 * i + dword_5004 + 40) = off_4E20[2 * i + 1];
      }
      *(_DWORD *)(dword_5004 + 132) = 2;
      ++dword_500C;
    }
    else
    {
      v2 = -2147479552;
    }
    pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
    _android_log_print(6, "qomx_image_core", "%s:%d] Complete %d", "OMX_Init");
    v0 = v2;
  }
  return v0;
}
// 808: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD);
// 4E20: using guessed type char *off_4E20[4];
// 5004: using guessed type int dword_5004;
// 500C: using guessed type int dword_500C;

//----- (00000B5C) --------------------------------------------------------
int OMX_Deinit()
{
  pthread_mutex_lock((pthread_mutex_t *)&unk_5008);
  if ( dword_500C == 1 && dword_5004 )
  {
    free((void *)dword_5004);
    dword_5004 = 0;
  }
  if ( dword_500C )
    --dword_500C;
  _android_log_print(6, "qomx_image_core", "%s:%d] Complete", "OMX_Deinit");
  pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
  return 0;
}
// 808: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD);
// 5004: using guessed type int dword_5004;
// 500C: using guessed type int dword_500C;

//----- (00000C0C) --------------------------------------------------------
signed int __fastcall sub_C0C(char *a1)
{
  signed int v1; // r3@2
  char *s2; // [sp+4h] [bp-14h]@1
  signed int v4; // [sp+8h] [bp-10h]@1
  signed int i; // [sp+Ch] [bp-Ch]@3

  s2 = a1;
  v4 = -1;
  if ( a1 )
  {
    for ( i = 0; *(_DWORD *)(dword_5004 + 132) > i; ++i )
    {
      if ( !strcmp(*(const char **)(44 * i + dword_5004 + 36), s2) )
      {
        v4 = i;
        break;
      }
    }
    v1 = v4;
  }
  else
  {
    v1 = -1;
  }
  return v1;
}
// 5004: using guessed type int dword_5004;

//----- (00000C84) --------------------------------------------------------
signed int __fastcall sub_C84(int a1)
{
  signed int v2; // [sp+8h] [bp-8h]@1
  signed int i; // [sp+Ch] [bp-4h]@1

  v2 = -1;
  for ( i = 0; i <= 2; ++i )
  {
    if ( !*(_DWORD *)(a1 + 4 * i) )
      return i;
  }
  return v2;
}

//----- (00000CC0) --------------------------------------------------------
signed int __fastcall OMX_GetHandle(_DWORD *a1, char *a2, int a3, int a4)
{
  signed int v4; // r3@2
  int v5; // ST04_4@17
  signed int result; // r0@21
  int v7; // [sp+18h] [bp-140h]@1
  int v8; // [sp+1Ch] [bp-13Ch]@1
  char *v9; // [sp+20h] [bp-138h]@1
  _DWORD *v10; // [sp+24h] [bp-134h]@1
  signed int v11; // [sp+2Ch] [bp-12Ch]@1
  signed int v12; // [sp+30h] [bp-128h]@3
  signed int v13; // [sp+34h] [bp-124h]@5
  int v14; // [sp+38h] [bp-120h]@1
  int v15; // [sp+3Ch] [bp-11Ch]@1
  int v16; // [sp+40h] [bp-118h]@1
  char s; // [sp+44h] [bp-114h]@1
  int v18; // [sp+144h] [bp-14h]@1

  v10 = a1;
  v9 = a2;
  v8 = a3;
  v7 = a4;
  v18 = _stack_chk_guard;
  memset(&s, 0, 0xFFu);
  v14 = 0;
  v15 = 0;
  v16 = 0;
  v11 = 0;
  if ( !v10 )
  {
    _android_log_print(6, "qomx_image_core", "%s:%d] Error invalid input ", "OMX_GetHandle");
    v4 = -2147479547;
    goto LABEL_21;
  }
  pthread_mutex_lock((pthread_mutex_t *)&unk_5008);
  v12 = sub_C0C(v9);
  if ( v12 < 0 )
  {
    _android_log_print(6, "qomx_image_core", "%s:%d] Cannot find the component", "OMX_GetHandle");
    pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
    v4 = -2147479548;
    goto LABEL_21;
  }
  v16 = 44 * v12 + dword_5004;
  *v10 = 0;
  v13 = sub_C84(v16);
  if ( v13 >= 0 )
  {
    if ( !*(_BYTE *)(v16 + 20) )
    {
      *(_DWORD *)(v16 + 24) = dlopen(*(const char **)(v16 + 40), 0);
      if ( !*(_DWORD *)(v16 + 24) )
      {
        _android_log_print(6, "qomx_image_core", "%s:%d] Cannot load the library", "OMX_GetHandle");
        goto LABEL_18;
      }
      *(_BYTE *)(v16 + 20) = 1;
      *(_DWORD *)(v16 + 32) = dlsym(*(void **)(v16 + 24), "create_component_fns");
      *(_DWORD *)(v16 + 28) = dlsym(*(void **)(v16 + 24), "getInstance");
      v11 = 1;
      if ( !*(_DWORD *)(v16 + 32) || !*(_DWORD *)(v16 + 28) )
      {
        _android_log_print(6, "qomx_image_core", "%s:%d] Cannot maps the symbols", "OMX_GetHandle");
        goto LABEL_18;
      }
    }
    v14 = (*(int (**)(void))(v16 + 28))();
    _android_log_print(6, "qomx_image_core", "%s:%d] get instance pts is %p", "OMX_GetHandle");
    if ( v14 )
    {
      v15 = (*(int (__fastcall **)(int))(v16 + 32))(v14);
      if ( v15 )
      {
        *(_DWORD *)(v16 + 4 * v13) = v15;
        *v10 = *(_DWORD *)(v16 + 4 * v13);
        v5 = *(_DWORD *)(v16 + 4 * v13);
        _android_log_print(
          3,
          "qomx_image_core",
          "%s:%d] handle = %x Instanceindex = %d,comp_idx %d g_ptr %p",
          "OMX_GetHandle");
        (*(void (__fastcall **)(int, int, int))(v15 + 72))(v15, v7, v8);
        pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
        _android_log_print(6, "qomx_image_core", "%s:%d] Success", "OMX_GetHandle");
        v4 = 0;
        goto LABEL_21;
      }
      _android_log_print(6, "qomx_image_core", "%s:%d] Error cannot create component", "OMX_GetHandle");
    }
    else
    {
      _android_log_print(6, "qomx_image_core", "%s:%d] Error cannot create object", "OMX_GetHandle");
    }
  }
  else
  {
    _android_log_print(6, "qomx_image_core", "%s:%d] Cannot alloc new instance", "OMX_GetHandle");
  }
LABEL_18:
  if ( v11 == 1 )
  {
    dlclose(*(void **)(v16 + 24));
    *(_DWORD *)(v16 + 24) = 0;
  }
  pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
  _android_log_print(6, "qomx_image_core", "%s:%d] Error %d", "OMX_GetHandle");
  v4 = -2147479548;
LABEL_21:
  result = v4;
  if ( v18 != _stack_chk_guard )
    _stack_chk_fail(v4);
  return result;
}
// 808: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD);
// 868: using guessed type int __fastcall _stack_chk_fail(_DWORD);
// 5004: using guessed type int dword_5004;

//----- (00001110) --------------------------------------------------------
signed int __fastcall sub_1110(int a1, _DWORD *a2, signed int *a3)
{
  signed int *v5; // [sp+14h] [bp-1Ch]@1
  _DWORD *v6; // [sp+18h] [bp-18h]@1
  int i; // [sp+20h] [bp-10h]@1
  signed int j; // [sp+24h] [bp-Ch]@2

  v6 = a2;
  v5 = a3;
  for ( i = 0; *(_DWORD *)(dword_5004 + 132) > i; ++i )
  {
    for ( j = 0; j <= 2; ++j )
    {
      if ( *(_DWORD *)(dword_5004 + 4 * (11 * i + j)) == a1 )
      {
        _android_log_print(6, "qomx_image_core", "%s:%d] comp_idx %d inst_idx %d", "get_idx_from_handle");
        *v6 = i;
        *v5 = j;
        return 1;
      }
    }
  }
  return 0;
}
// 808: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD);
// 5004: using guessed type int dword_5004;

//----- (000011C4) --------------------------------------------------------
signed int __fastcall sub_11C4(int a1)
{
  unsigned __int8 i; // [sp+Fh] [bp-1h]@1

  for ( i = 0; i <= 2u; ++i )
  {
    if ( *(_DWORD *)(a1 + 4 * i) )
      return 1;
  }
  return 0;
}

//----- (00001204) --------------------------------------------------------
signed int __fastcall OMX_FreeHandle(int a1)
{
  signed int v1; // r3@2
  int v3; // [sp+Ch] [bp-24h]@1
  int v4; // [sp+14h] [bp-1Ch]@3
  int v5; // [sp+18h] [bp-18h]@3
  int v6; // [sp+1Ch] [bp-14h]@1
  int v7; // [sp+20h] [bp-10h]@1
  int v8; // [sp+24h] [bp-Ch]@1

  v3 = a1;
  v6 = 0;
  v7 = 0;
  v8 = 0;
  _android_log_print(6, "qomx_image_core", "%s:%d] ", "OMX_FreeHandle");
  if ( v3 )
  {
    pthread_mutex_lock((pthread_mutex_t *)&unk_5008);
    v7 = v3;
    if ( sub_1110(v3, &v4, &v5) )
    {
      v6 = (*(int (__fastcall **)(int))(v7 + 76))(v3);
      if ( v6 )
      {
        _android_log_print(6, "qomx_image_core", "%s:%d] Error comp deinit failed", "OMX_FreeHandle");
        pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
        v1 = -2147479548;
      }
      else
      {
        v8 = 44 * v4 + dword_5004;
        *(_DWORD *)(v8 + 4 * v5) = 0;
        if ( sub_11C4(v8) )
        {
          _android_log_print(6, "qomx_image_core", "%s:%d] Error Component is still Active", "OMX_FreeHandle");
        }
        else
        {
          v6 = dlclose(*(void **)(v8 + 24));
          *(_DWORD *)(v8 + 24) = 0;
          *(_DWORD *)(v8 + 28) = 0;
          *(_DWORD *)(v8 + 32) = 0;
          *(_BYTE *)(v8 + 20) = 0;
        }
        pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
        _android_log_print(6, "qomx_image_core", "%s:%d] Success", "OMX_FreeHandle");
        v1 = v6;
      }
    }
    else
    {
      _android_log_print(6, "qomx_image_core", "%s:%d] Error invalid component", "OMX_FreeHandle");
      pthread_mutex_unlock((pthread_mutex_t *)&unk_5008);
      v1 = -2147479548;
    }
  }
  else
  {
    v1 = -2147479547;
  }
  return v1;
}
// 808: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD, _DWORD);
// 5004: using guessed type int dword_5004;

//----- (000013C4) --------------------------------------------------------
signed int __fastcall sub_13C4(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // r5@1
  unsigned int v5; // r7@1
  int v6; // r10@1
  int v7; // r4@1
  int v8; // r11@2
  unsigned int v9; // r8@7
  int v10; // r9@7
  int v11; // r0@8
  int v12; // r2@9
  int v13; // r1@10
  signed int result; // r0@10
  int v15; // r3@19
  int v16; // r2@19
  int v17; // r0@19
  int v18; // r1@19
  int v19; // r2@37
  int v20; // r0@39
  int v21; // r1@39
  int v22; // r3@39
  unsigned int v23; // r1@40
  unsigned int v24; // r0@40
  int v25; // r1@42
  int v26; // r6@45
  char v27; // r1@45
  int v29; // r0@50
  unsigned int v35; // r0@51
  int v36; // [sp+4h] [bp-34h]@58
  int v37; // [sp+8h] [bp-30h]@6
  int v38; // [sp+Ch] [bp-2Ch]@22
  int v39; // [sp+10h] [bp-28h]@8

  v4 = a4;
  v5 = a3;
  v6 = a2;
  v7 = a1;
  if ( a3 >= a4 )
    goto LABEL_58;
  v8 = 0;
  do
  {
    v9 = v5 + 1;
    v10 = *(_BYTE *)(v6 + (v5 ^ 3));
    if ( !(v10 & 0x80) )
    {
      sub_1C40(v7, 13, &v39);
      v11 = 4 * v10;
      if ( v10 & 0x40 )
        v12 = -4 - (v11 & 0xFC) + v39;
      else
        v12 = v11 + v39 + 4;
      v39 = v12;
LABEL_23:
      sub_1C70(v7, 13, v12);
      ++v5;
      continue;
    }
    v13 = v10 & 0xF0;
    result = 9;
    if ( v13 > 159 )
    {
      if ( v13 > 191 )
      {
        if ( v13 == 192 )
        {
          switch ( v10 )
          {
            case 199:
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || (unsigned int)*(_BYTE *)(v6 + (v9 ^ 3)) >= 0x10 )
                return 9;
              goto LABEL_55;
            case 192:
            case 193:
            case 194:
            case 195:
            case 196:
            case 197:
              v18 = 3;
              v16 = ((v10 & 7) + 1) | 0xA0000;
              v17 = v7;
              goto LABEL_33;
            case 200:
            case 201:
              v23 = *(_BYTE *)(v6 + (v9 ^ 3));
              v24 = v23 >> 4;
              if ( v10 == 200 )
                v24 = (v23 >> 4) | 0x10;
              v25 = v23 & 0xF;
              if ( (signed int)(v24 + v25) > 31 )
                return 9;
              v19 = (v25 + 1) | (v24 << 16);
              v20 = v7;
              v21 = 1;
              goto LABEL_53;
            case 198:
              v35 = *(_BYTE *)(v6 + (v9 ^ 3));
              if ( (signed int)((v35 & 0xF) + (v35 >> 4)) > 15 )
                return 9;
              v19 = ((v35 & 0xF) + 1) | (v35 >> 4 << 16);
              v20 = v7;
              v21 = 3;
LABEL_53:
              v22 = 5;
LABEL_54:
              sub_17A8(v20, v21, v19, v22);
              goto LABEL_55;
            default:
              return 9;
          }
          return 9;
        }
        if ( v13 != 208 )
          return result;
        if ( v10 & 8 )
          return 9;
        v18 = 1;
        v16 = ((v10 & 7) + 1) | 0x80000;
        v17 = v7;
LABEL_33:
        v15 = 5;
      }
      else
      {
        if ( v13 != 160 )
        {
          if ( v13 != 176 )
            return result;
          result = 9;
          switch ( v10 )
          {
            case 177:
              if ( v9 >= v4 )
                return 9;
              v19 = *(_BYTE *)(v6 + (v9 ^ 3));
              result = 9;
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || v19 & 0xF0 )
                return result;
              v20 = v7;
              v21 = 0;
              v22 = 0;
              goto LABEL_54;
            case 178:
              if ( v9 >= v4 )
                return 9;
              v5 += 2;
              v26 = 0;
              v27 = 0;
              break;
            case 179:
              v22 = 1;
              v29 = *(_BYTE *)(v6 + (v9 ^ 3));
              _R1 = v29 << 12;
              __asm { UXTB16.W        R1, R1 }
              v19 = ((v29 & 0xF) + 1) | _R1;
              v20 = v7;
              v21 = 1;
              goto LABEL_54;
            case 176:
              goto LABEL_57;
            case 180:
            case 181:
            case 182:
            case 183:
              return result;
            default:
              v18 = 1;
              v15 = 1;
              v16 = ((v10 & 7) + 1) | 0x80000;
              v17 = v7;
              goto LABEL_34;
          }
          while ( 1 )
          {
            v26 |= (*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x7F) << v27;
            if ( !(*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x80) )
              break;
            v27 += 7;
            _CF = v5 >= v4;
            result = 9;
            ++v5;
            if ( _CF )
              return result;
          }
          sub_1C40(v7, 13, &v37);
          v37 += 4 * v26 + 516;
          sub_1C70(v7, 13, v37);
          continue;
        }
        v15 = 0;
        v16 = ((16 << ((*(_BYTE *)(v6 + (v5 ^ 3)) & 7) + 1)) - 16) | (*(_BYTE *)(v6 + (v5 ^ 3)) << 11) & 0x4000;
        v17 = v7;
        v18 = 0;
      }
LABEL_34:
      sub_17A8(v17, v18, v16, v15);
      ++v5;
      continue;
    }
    if ( v13 != 128 )
    {
      if ( v13 != 144 )
        return result;
      if ( (v10 & 0xF | 2) == 15 )
        return 9;
      sub_1C40(v7, v10 & 0xF, &v38);
      v12 = v38;
      goto LABEL_23;
    }
    if ( v9 >= v4 || !((unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + ((v5 + 1) ^ 3))) )
      return 9;
    sub_17A8(v7, 0, (unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + (v9 ^ 3)), 0);
    v8 |= (((_WORD)v10 << 12) & 0x8000u) >> 15;
LABEL_55:
    v5 += 2;
  }
  while ( v5 < v4 );
LABEL_57:
  if ( v8 & 1 )
    return 8;
LABEL_58:
  sub_1C40(v7, 14, &v36);
  sub_1C70(v7, 15, v36);
  return 8;
}

//----- (00001704) --------------------------------------------------------
signed int __fastcall sub_1704(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int v5; // r5@1
  int v6; // r4@1
  signed int result; // r0@2
  int v8; // r2@4
  int v9; // r0@4
  int v10; // r1@4
  __int64 v11; // r2@10
  int v12; // r1@10

  v5 = a3;
  v6 = a1;
  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = v6;
      v10 = v5;
      goto LABEL_14;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_21;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_1D5C(a1);
LABEL_21:
      v11 = *(_QWORD *)a5;
      v12 = v5 + 256;
LABEL_22:
      result = sub_1CE4(v6, v12, v11, SHIDWORD(v11));
LABEL_23:
      if ( result )
        result = 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = v5 + 112;
      goto LABEL_22;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = v5 + 192;
      v9 = v6;
LABEL_14:
      result = sub_1C70(v9, v10, v8);
      goto LABEL_23;
    default:
      sub_1AE4(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepre"
             "sentation, void *)",
        831,
        (int)"unsupported register class");
      return result;
  }
}

//----- (000017A8) --------------------------------------------------------
signed int __fastcall sub_17A8(int a1, int a2, unsigned int a3, int a4)
{
  int v4; // r5@1
  int v5; // r7@1
  unsigned int v6; // r6@1
  int v7; // r8@1
  int v8; // r4@4
  unsigned int v9; // r7@4
  int *v10; // r0@6
  signed int v11; // r0@6
  signed int v12; // r1@6
  signed int v13; // r2@6
  signed int result; // r0@14
  unsigned int v15; // r4@18
  unsigned int v16; // r6@18
  int v17; // r0@19
  int v18; // r2@19
  int v19; // r2@22
  int v20; // [sp+8h] [bp-38h]@19
  int v21; // [sp+Ch] [bp-34h]@19
  int v22; // [sp+14h] [bp-2Ch]@16
  int v23; // [sp+18h] [bp-28h]@6
  int *v24; // [sp+1Ch] [bp-24h]@3

  v4 = a2;
  v5 = a4;
  v6 = a3;
  v7 = a1;
  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_1C40(a1, 13, &v24) )
        return 2;
      v8 = 0;
      v9 = 0;
      do
      {
        if ( (1 << v9) & v6 )
        {
          v10 = v24;
          ++v24;
          v23 = *v10;
          v11 = sub_1704(v7, v4, v9, 0, &v23);
          v12 = 0;
          v13 = 0;
          if ( v9 == 13 )
            v12 = 1;
          if ( !v4 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
        ++v9;
      }
      while ( v9 < 0x10 );
      if ( v8 & 1 )
        return 0;
      v19 = (int)v24;
      goto LABEL_28;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_1C40(a1, 13, &v22) )
        return 2;
      if ( !(_WORD)v6 )
        goto LABEL_21;
      v15 = v6 >> 16;
      v16 = (v6 >> 16) + v6;
      break;
    default:
      sub_1AE4(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        965,
        (int)"unsupported register class");
      return result;
  }
  do
  {
    v17 = v22;
    v22 += 4;
    v18 = *(_DWORD *)v17;
    v22 = v17 + 8;
    v21 = *(_DWORD *)(v17 + 4);
    v20 = v18;
    if ( sub_1704(v7, v4, v15, v5, &v20) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( v5 == 1 )
  {
    v19 = v22 + 4;
    v22 += 4;
  }
  else
  {
    v19 = v22;
  }
LABEL_28:
  result = sub_1C70(v7, 13, v19);
  if ( result )
    result = 2;
  return result;
}

//----- (000018D0) --------------------------------------------------------
signed int __fastcall sub_18D0(int a1, int a2, int a3)
{
  int v3; // r0@1
  int v4; // r1@1
  unsigned int *v5; // r12@1
  int v6; // r3@1
  bool v7; // zf@2
  unsigned int v8; // r3@6
  unsigned int v9; // r2@6

  v3 = a2;
  v4 = a3;
  v5 = *(unsigned int **)(v3 + 76);
  v6 = (*v5 >> 24) & 0xF;
  if ( v6 )
  {
    v7 = v6 == 1;
    if ( v6 != 1 )
      v7 = v6 == 3;
    if ( !v7 )
      return 9;
    v8 = 4 * ((*v5 >> 16) & 0xFF) + 4;
    v9 = 2;
  }
  else
  {
    v9 = 1;
    v8 = 4;
  }
  if ( !v5 || !(*(_BYTE *)(v3 + 80) & 1) && *(unsigned int *)((char *)v5 + v8) )
    return 9;
  return sub_13C4(v4, (int)v5, v9, v8);
}

//----- (00001924) --------------------------------------------------------
void sub_1924()
{
  JUMPOUT(&loc_18D8);
}

//----- (0000192C) --------------------------------------------------------
void sub_192C()
{
  JUMPOUT(&loc_18D8);
}

//----- (000019C8) --------------------------------------------------------
signed int __fastcall sub_19C8(int a1, int a2, char a3)
{
  int v3; // r4@1
  char v4; // r10@1
  signed int i; // r6@1
  signed int v6; // r7@3
  int v7; // r0@8
  int (__fastcall *v8)(signed int, int, char *); // r3@11
  int v9; // r0@12
  int v11; // [sp+0h] [bp-4B0h]@17
  int v12; // [sp+4h] [bp-4ACh]@10
  int (__fastcall *v13)(signed int, int, char *); // [sp+10h] [bp-4A0h]@11
  int v14; // [sp+18h] [bp-498h]@12
  int v15; // [sp+24h] [bp-48Ch]@12
  int v16; // [sp+2Ch] [bp-484h]@10
  char v17; // [sp+30h] [bp-480h]@1

  v3 = a2;
  v4 = a3;
  sub_1BF0((int)&v17);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( v4 & 1 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_1C70((int)&v17, -1, *(_DWORD *)(v3 + 16));
        v4 = 0;
      }
    }
    v7 = sub_1D1C((int)&v17);
    if ( !v7 )
      break;
    if ( v7 < 0 )
      return 2;
    sub_1C40((int)&v17, -2, &v16);
    if ( sub_1D24((int)&v17, (int)&v12) )
      return 2;
    v8 = v13;
    if ( v13 )
    {
      *(_DWORD *)(v3 + 72) = v12;
      *(_DWORD *)(v3 + 76) = v15;
      *(_DWORD *)(v3 + 80) = v14;
      v9 = v8(v6, v3, &v17);
      if ( v9 == 7 )
      {
        sub_1C40((int)&v17, -1, &v11);
        *(_DWORD *)(v3 + 16) = v11;
        sub_1D44((int)&v17);
        return 2;
      }
      if ( v9 == 9 )
        abort();
      if ( v9 != 8 )
        return 2;
      if ( v16 == *(_DWORD *)(v3 + 32) )
        sub_1AE4(
          (int)"_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          642,
          (int)"during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return 5;
}

//----- (00001AE4) --------------------------------------------------------
void __fastcall sub_1AE4(int a1, int a2, int a3)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libcxxabi/src/Unwind/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (00001B68) --------------------------------------------------------
int __fastcall sub_1B68(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4@0
  int v6; // r5@0
  int v7; // r6@0
  int v8; // r7@0
  int v9; // r8@0
  int v10; // r9@0
  int v11; // r10@0
  int v12; // r11@0
  int v13; // r12@0
  int v14; // lr@0

  *(_DWORD *)a1 = a1;
  *(_DWORD *)(a1 + 4) = a2;
  *(_DWORD *)(a1 + 8) = a3;
  *(_DWORD *)(a1 + 12) = a4;
  *(_DWORD *)(a1 + 16) = v5;
  *(_DWORD *)(a1 + 20) = v6;
  *(_DWORD *)(a1 + 24) = v7;
  *(_DWORD *)(a1 + 28) = v8;
  *(_DWORD *)(a1 + 32) = v9;
  *(_DWORD *)(a1 + 36) = v10;
  *(_DWORD *)(a1 + 40) = v11;
  *(_DWORD *)(a1 + 44) = v12;
  *(_DWORD *)(a1 + 48) = v13;
  *(_DWORD *)(a1 + 52) = &a5;
  *(_DWORD *)(a1 + 56) = v14;
  *(_DWORD *)(a1 + 60) = v14;
  return 0;
}

//----- (00001B80) --------------------------------------------------------
int __fastcall sub_1B80(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (00001B88) --------------------------------------------------------
int __fastcall sub_1B88(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (00001B90) --------------------------------------------------------
int __fastcall sub_1B90(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D16-D31} }
  return result;
}

//----- (00001B98) --------------------------------------------------------
void sub_1B98()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (00001BDC) --------------------------------------------------------
void sub_1BDC()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (00001BF0) --------------------------------------------------------
int __fastcall sub_1BF0(int a1)
{
  int v1; // r4@1

  v1 = a1;
  *(_DWORD *)a1 = &off_4E38;
  *(_DWORD *)(a1 + 4) = &unk_5010;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  _aeabi_memcpy(a1 + 8);
  _aeabi_memset(v1 + 80, 450, 0);
  sub_2164(v1, 0);
  return 0;
}
// 88C: using guessed type int __fastcall _aeabi_memcpy(_DWORD);
// 898: using guessed type int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD);
// 4E38: using guessed type void *;

//----- (00001C40) --------------------------------------------------------
signed int __fastcall sub_1C40(int a1, int a2, _DWORD *a3)
{
  int v3; // r6@1
  _DWORD *v4; // r4@1
  int v5; // r5@1
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    *v4 = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 12))(v3, v5);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00001C70) --------------------------------------------------------
signed int __fastcall sub_1C70(int a1, int a2, int a3)
{
  int v3; // r4@1
  int v4; // r6@1
  int v5; // r5@1
  signed int v6; // r5@3

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v3 + 16))(v3, v5, v4);
    if ( v5 == -1 )
    {
      v6 = 0;
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 52))(v3, 0);
    }
    else
    {
      v6 = 0;
    }
  }
  else
  {
    v6 = -6542;
  }
  return v6;
}

//----- (00001CB4) --------------------------------------------------------
signed int __fastcall sub_1CB4(int a1, int a2, _QWORD *a3)
{
  int v3; // r6@1
  _QWORD *v4; // r4@1
  int v5; // r5@1
  __int64 v6; // r0@2
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 24))(v3, v5);
    *v4 = v6;
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00001CE4) --------------------------------------------------------
signed int __fastcall sub_1CE4(int a1, int a2, int a3, int a4)
{
  int v4; // r7@1
  int v5; // r5@1
  int v6; // r6@1
  int v7; // r8@1
  signed int result; // r0@2

  v4 = a1;
  v5 = a3;
  v6 = a2;
  v7 = a4;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)v4 + 28))(v4, v6, v5, v7);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00001D1C) --------------------------------------------------------
int __fastcall sub_1D1C(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 32))();
}

//----- (00001D24) --------------------------------------------------------
signed int __fastcall sub_1D24(int a1, int a2)
{
  int v2; // r4@1
  signed int result; // r0@1

  v2 = a2;
  (*(void (**)(void))(*(_DWORD *)a1 + 36))();
  result = 0;
  if ( !*(_DWORD *)(v2 + 4) )
    result = -6549;
  return result;
}

//----- (00001D44) --------------------------------------------------------
signed int __fastcall sub_1D44(int a1)
{
  (*(void (**)(void))(*(_DWORD *)a1 + 40))();
  return -6540;
}

//----- (00001D5C) --------------------------------------------------------
int __fastcall sub_1D5C(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 60))();
}

//----- (00001D6C) --------------------------------------------------------
int __fastcall sub_1D6C(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (00001D8C) --------------------------------------------------------
int __fastcall sub_1D8C(int a1, signed int a2)
{
  signed int v2; // r5@1
  int v3; // r4@1
  int v4; // r0@7

  v2 = a2;
  v3 = a1;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_21C4(
        (int)"uint32_t libunwind::Registers_arm::getRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1452,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_1BDC();
    }
    v4 = v3 + 4 * v2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (00001E28) --------------------------------------------------------
int __fastcall sub_1E28(int result, signed int a2, int a3)
{
  signed int v3; // r6@1
  int v4; // r4@1
  int v5; // r5@1

  v3 = a2;
  v4 = a3;
  v5 = result;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        *(_DWORD *)(result + 64) = a3;
        return result;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      *(_DWORD *)(result + 60) = a3;
      return result;
    }
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_21C4(
        (int)"void libunwind::Registers_arm::setRegister(int, uint32_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1471,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_1BDC();
    }
    result = v5 + 4 * v3;
    *(_DWORD *)(result - 296) = v4;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (00001EC0) --------------------------------------------------------
int __fastcall sub_1EC0(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (00001EE0) --------------------------------------------------------
__int64 __fastcall sub_1EE0(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r5@1
  unsigned int v4; // r0@1
  int v5; // r0@5
  int v6; // r0@11

  v2 = a2;
  v3 = a1;
  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v3 + 75) )
    {
      *(_BYTE *)(v3 + 75) = 1;
      sub_1B98();
    }
    v5 = v3 + 8 * v2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(v3 + 74) )
    {
      *(_BYTE *)(v3 + 74) = 1;
      sub_1B90(v3 + 216);
    }
    v5 = v3 + 8 * v2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_21C4(
        (int)"unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1673,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v3 + 73) )
    {
      *(_BYTE *)(v3 + 73) = 1;
      v6 = v3 + 80;
      if ( *(_BYTE *)(v3 + 72) )
        sub_1B88(v6);
      else
        sub_1B80(v6);
    }
    v5 = v3 + 8 * v2 - 1968;
  }
  return *(_QWORD *)v5;
}

//----- (00001F90) --------------------------------------------------------
int __fastcall sub_1F90(int a1, int a2, int a3, int a4)
{
  int v4; // r6@1
  int v5; // r7@1
  unsigned int v6; // r0@1
  int v7; // r5@1
  int v8; // r4@1
  int result; // r0@5
  int v10; // r1@5
  int v11; // r0@11

  v4 = a2;
  v5 = a1;
  v6 = a2 & 0xFFFFFFF0;
  v7 = a4;
  v8 = a3;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v5 + 75) )
    {
      *(_BYTE *)(v5 + 75) = 1;
      sub_1B98();
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 548) = v7;
    LOWORD(v10) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(v5 + 74) )
    {
      *(_BYTE *)(v5 + 74) = 1;
      sub_1B90(v5 + 216);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1828) = v7;
    LOWORD(v10) = -1832;
  }
  else
  {
    if ( v6 != 256 )
      sub_21C4(
        (int)"void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1700,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v5 + 73) )
    {
      *(_BYTE *)(v5 + 73) = 1;
      v11 = v5 + 80;
      if ( *(_BYTE *)(v5 + 72) )
        sub_1B88(v11);
      else
        sub_1B80(v11);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1964) = v7;
    LOWORD(v10) = -1968;
  }
  HIWORD(v10) = -1;
  *(_DWORD *)(result + v10) = v8;
  return result;
}

//----- (00002064) --------------------------------------------------------
signed int __fastcall sub_2064(int a1)
{
  int v1; // r4@1
  signed int result; // r0@3
  void (__fastcall *v3)(int, signed int, int); // r5@5
  int v4; // r0@5

  v1 = a1;
  if ( *(_BYTE *)(a1 + 528)
    || ((*(void (__fastcall **)(int, signed int))(*(_DWORD *)a1 + 52))(a1, 1), *(_BYTE *)(v1 + 528)) )
  {
    result = 0;
  }
  else
  {
    if ( *(_DWORD *)(v1 + 504) )
    {
      v3 = *(void (__fastcall **)(int, signed int, int))(*(_DWORD *)v1 + 16);
      v4 = (*(int (__fastcall **)(int, signed int))(*(_DWORD *)v1 + 12))(v1, -2);
      v3(v1, -2, *(_DWORD *)(v1 + 504) + v4);
    }
    result = 1;
  }
  return result;
}

//----- (000020B0) --------------------------------------------------------
int __fastcall sub_20B0(int a1, int a2)
{
  int v2; // r12@1
  int v3; // lr@1
  int v4; // r11@1
  int v5; // r3@1
  int v6; // r4@1
  int v7; // r5@1
  int v8; // r4@1
  int v9; // r2@1
  int v10; // r3@1
  int v11; // r5@1
  int result; // r0@1

  v2 = *(_DWORD *)(a1 + 488);
  v3 = *(_DWORD *)(a1 + 492);
  v4 = a2 + 8;
  v5 = *(_DWORD *)(a1 + 500);
  v6 = *(_DWORD *)(a1 + 504);
  v7 = *(_DWORD *)(a1 + 508);
  *(_DWORD *)v4 = *(_DWORD *)(a1 + 496);
  *(_DWORD *)(v4 + 4) = v5;
  *(_DWORD *)(v4 + 8) = v6;
  *(_DWORD *)(v4 + 12) = v7;
  v8 = a2 + 24;
  *(_DWORD *)a2 = v2;
  *(_DWORD *)(a2 + 4) = v3;
  v9 = *(_DWORD *)(a1 + 512);
  v10 = *(_DWORD *)(a1 + 516);
  v11 = *(_DWORD *)(a1 + 520);
  result = *(_DWORD *)(a1 + 524);
  *(_DWORD *)(a2 + 36) = result;
  *(_DWORD *)v8 = v9;
  *(_DWORD *)(v8 + 4) = v10;
  *(_DWORD *)(v8 + 8) = v11;
  return result;
}

//----- (000020E8) --------------------------------------------------------
void __fastcall sub_20E8(int a1)
{
  sub_21F8(a1 + 8);
  sub_2B2C();
}

//----- (00002100) --------------------------------------------------------
int __fastcall sub_2100(int a1)
{
  return *(_BYTE *)(a1 + 529);
}

//----- (00002108) --------------------------------------------------------
signed int __fastcall sub_2108(int a1, int a2, int a3, _DWORD *a4)
{
  int v4; // r6@1
  int v5; // r5@1
  _DWORD *v6; // r4@1
  int v7; // r7@1
  int v8; // r0@1
  bool v9; // zf@1
  signed int result; // r0@4
  int v11; // [sp+10h] [bp-20h]@2
  int v12; // [sp+14h] [bp-1Ch]@4

  v4 = a2;
  v5 = a3;
  v6 = a4;
  v7 = (*(int (**)(void))(*(_DWORD *)a1 + 12))();
  v8 = dladdr();
  v9 = v8 == 0;
  if ( v8 )
    v9 = v11 == 0;
  if ( v9 )
  {
    result = 0;
  }
  else
  {
    _snprintf_chk(v4, v5, 0, -1);
    *v6 = v7 - v12;
    result = 1;
  }
  return result;
}
// 8A4: using guessed type int dladdr(void);
// 8B0: using guessed type int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00002164) --------------------------------------------------------
int __fastcall sub_2164(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r6@1
  unsigned int v4; // r5@1
  int v5; // r0@3
  bool v6; // zf@3
  int result; // r0@6
  int v8; // [sp+4h] [bp-1Ch]@3
  int v9; // [sp+8h] [bp-18h]@3
  int v10; // [sp+Ch] [bp-14h]@1

  v2 = a1;
  v3 = a2;
  v4 = (*(int (**)(void))(*(_DWORD *)a1 + 12))() & 0xFFFFFFFE;
  v10 = 0;
  if ( v3 )
    --v4;
  v5 = _gnu_Unwind_Find_exidx(v4, &v10);
  v6 = v5 == 0;
  v8 = v5;
  v9 = v10;
  if ( v5 )
    v6 = v10 == 0;
  if ( v6 || (result = ((int (__fastcall *)(int, unsigned int, int *))sub_224C)(v2, v4, &v8)) == 0 )
  {
    result = 1;
    *(_BYTE *)(v2 + 528) = 1;
  }
  return result;
}
// 8BC: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);
// 224C: using guessed type int sub_224C();

//----- (000021B4) --------------------------------------------------------
const char *__fastcall sub_21B4(int a1, signed int a2)
{
  const char *result; // r0@2
  signed int v3; // r1@3
  int *v4; // r0@3

  if ( a2 > 255 )
  {
    switch ( a2 )
    {
      case 256:
        v3 = -6890;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 257:
        v3 = -6887;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 258:
        v3 = -6884;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 259:
        v3 = -6881;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 260:
        v3 = -6878;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 261:
        v3 = -6875;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 262:
        v3 = -6872;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 263:
        v3 = -6869;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 264:
        v3 = -6866;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 265:
        v3 = -6863;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 266:
        v3 = -6860;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 267:
        v3 = -6856;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 268:
        v3 = -6852;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 269:
        v3 = -6848;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 270:
        v3 = -6844;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 271:
        v3 = -6840;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 272:
        v3 = -6836;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 273:
        v3 = -6832;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 274:
        v3 = -6828;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 275:
        v3 = -6824;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 276:
        v3 = -6820;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 277:
        v3 = -6816;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 278:
        v3 = -6812;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 279:
        v3 = -6808;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 280:
        v3 = -6804;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 281:
        v3 = -6800;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 282:
        v3 = -6796;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 283:
        v3 = -6792;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 284:
        v3 = -6788;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 285:
        v3 = -6784;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 286:
        v3 = -6780;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 287:
        v3 = -6776;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      default:
def_2520:
        v3 = -6772;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  else
  {
    result = "pc";
    switch ( a2 + 2 )
    {
      case 0:
      case 15:
        v3 = -7053;
        v4 = &GLOBAL_OFFSET_TABLE_;
        return (char *)v4 + v3;
      default:
        goto def_2520;
      case 1:
      case 17:
        return result;
      case 2:
        v3 = -7050;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 3:
        v3 = -7047;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 4:
        v3 = -7044;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 5:
        v3 = -7041;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 6:
        v3 = -7038;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 7:
        v3 = -7035;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 8:
        v3 = -7032;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 9:
        v3 = -7029;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 10:
        v3 = -7026;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 11:
        v3 = -7023;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 12:
        v3 = -7020;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 13:
        v3 = -7016;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 14:
        v3 = -7012;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 16:
        v3 = -7056;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 66:
        v3 = -7008;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 67:
        v3 = -7005;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 68:
        v3 = -7002;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 69:
        v3 = -6999;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 70:
        v3 = -6996;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 71:
        v3 = -6993;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 72:
        v3 = -6990;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 73:
        v3 = -6987;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 74:
        v3 = -6984;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 75:
        v3 = -6981;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 76:
        v3 = -6978;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 77:
        v3 = -6974;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 78:
        v3 = -6970;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 79:
        v3 = -6966;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 80:
        v3 = -6962;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 81:
        v3 = -6958;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 82:
        v3 = -6954;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 83:
        v3 = -6950;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 84:
        v3 = -6946;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 85:
        v3 = -6942;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 86:
        v3 = -6938;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 87:
        v3 = -6934;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 88:
        v3 = -6930;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 89:
        v3 = -6926;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 90:
        v3 = -6922;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 91:
        v3 = -6918;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 92:
        v3 = -6914;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 93:
        v3 = -6910;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 94:
        v3 = -6906;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 95:
        v3 = -6902;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 96:
        v3 = -6898;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 97:
        v3 = -6894;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  return (char *)v4 + v3;
}
// 4FA0: using guessed type int GLOBAL_OFFSET_TABLE_;

//----- (000021BC) --------------------------------------------------------
int __fastcall sub_21BC(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (000021C4) --------------------------------------------------------
void __fastcall sub_21C4(int a1, int a2, int a3, int a4)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (000021F8) --------------------------------------------------------
int __fastcall sub_21F8(int a1)
{
  int v1; // r4@1
  int v2; // r0@2
  int result; // r0@9

  v1 = a1;
  if ( *(_BYTE *)(a1 + 65) )
  {
    v2 = a1 + 72;
    if ( *(_BYTE *)(v1 + 64) )
      sub_2AC4(v2);
    else
      sub_2ABC(v2);
  }
  if ( *(_BYTE *)(v1 + 66) )
    sub_2ACC(v1 + 208);
  if ( *(_BYTE *)(v1 + 67) )
    sub_2AD4((_DWORD *)(v1 + 336));
  result = *(_BYTE *)(v1 + 68);
  if ( *(_BYTE *)(v1 + 68) )
    result = sub_2B3C((_DWORD *)(v1 + 464));
  return result;
}

//----- (000023D4) --------------------------------------------------------
int __fastcall sub_23D4(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4@1
  unsigned int v9; // r5@2
  int v10; // r6@3

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + (2 * *(_DWORD *)(*a4 + 8 * v10) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = a3;
  *(_DWORD *)(result + 8) = a4;
  return result;
}

//----- (00002ABC) --------------------------------------------------------
int __fastcall sub_2ABC(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (00002AC4) --------------------------------------------------------
int __fastcall sub_2AC4(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (00002ACC) --------------------------------------------------------
int __fastcall sub_2ACC(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D16-D31} }
  return result;
}

//----- (00002AD4) --------------------------------------------------------
int __fastcall sub_2AD4(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = (int)(v5 + 2);
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (00002B18) --------------------------------------------------------
int __fastcall sub_2B18(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = (int)(v5 + 1);
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (00002B2C) --------------------------------------------------------
void sub_2B2C()
{
  sub_2B30();
}

//----- (00002B30) --------------------------------------------------------
void sub_2B30()
{
  JUMPOUT(sub_2AA8);
}
// 2AA8: using guessed type int sub_2AA8();

//----- (00002B3C) --------------------------------------------------------
int __fastcall sub_2B3C(_DWORD *a1)
{
  return sub_2B40(a1);
}

//----- (00002B40) --------------------------------------------------------
int __fastcall sub_2B40(_DWORD *a1)
{
  return sub_2B18(a1);
}

// ALL OK, 59 function(s) have been successfully decompiled
